[workspace]
members = ["datafusion-loki", "datafusion-loki/gen", "integration-tests"]
resolver = "3"

[workspace.dependencies]
datafusion = "55"
datafusion-catalog = "55"
datafusion-common = "55"
datafusion-datasource = "55"
datafusion-execution = "55"
datafusion-expr = "55"
datafusion-functions = "55"
datafusion-physical-expr = "55"
datafusion-physical-plan = "55"
datafusion-proto = "55"

arrow = "59"
parquet = "59"

prost = "0.13"
prost-build = "0.13"
tokio = "1"
