// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LokiPhysicalPlanNode {
    #[prost(oneof = "loki_physical_plan_node::LokiPhysicalPlanType", tags = "1, 2")]
    pub loki_physical_plan_type:
        ::core::option::Option<loki_physical_plan_node::LokiPhysicalPlanType>,
}
/// Nested message and enum types in `LokiPhysicalPlanNode`.
pub mod loki_physical_plan_node {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum LokiPhysicalPlanType {
        #[prost(message, tag = "1")]
        Scan(super::LokiLogScanExec),
        #[prost(message, tag = "2")]
        Insert(super::LokiLogInsertExec),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LokiLogScanExec {
    #[prost(string, tag = "1")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub log_query: ::prost::alloc::string::String,
    #[prost(int64, optional, tag = "3")]
    pub start: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub end: ::core::option::Option<i64>,
    #[prost(message, optional, tag = "5")]
    pub projection: ::core::option::Option<Projection>,
    #[prost(int32, optional, tag = "6")]
    pub limit: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LokiLogInsertExec {
    #[prost(string, tag = "1")]
    pub endpoint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Projection {
    #[prost(uint32, repeated, tag = "1")]
    pub projection: ::prost::alloc::vec::Vec<u32>,
}
